apiVersion: apps/v1
kind: Deployment
metadata:
  name: reader
  labels:
    app: reader
  annotations:
    # Annotation for Litmus
    litmuschaos.io/chaos: "true"
spec:
  selector:
    matchLabels:
      app: reader
  template:
    metadata:
      labels:
        app: reader
      annotations:
        # Annotation for Litmus
        litmuschaos.io/chaos: "true"
    spec:
      containers:
        - name: reader
          image: iskorotkov/chaos-client:v0.1.0
          args:
            - "-host"
            - "$(SERVER_SERVICE_HOST)"
            - "-verb"
            - "get"
            - "-rate"
            - "1"
          resources:
            limits:
              memory: "64Mi"
              cpu: "50m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: writer
  labels:
    app: writer
  annotations:
    # Annotation for Litmus
    litmuschaos.io/chaos: "true"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: writer
  template:
    metadata:
      labels:
        app: writer
      annotations:
        # Annotation for Litmus
        litmuschaos.io/chaos: "true"
    spec:
      containers:
        - name: writer
          image: iskorotkov/chaos-client:v0.1.0
          args:
            - "-host"
            - "$(SERVER_SERVICE_HOST)"
            - "-verb"
            - "post"
            - "-rate"
            - "1"
          resources:
            limits:
              memory: "64Mi"
              cpu: "50m"
